[tools]
python = {version="3.10.11", virtualenv="server/.venv"}
node = "21.7.3"

[settings]
# mise runを使うための設定
experimental = true


# miseで実行するタスクの設定

# セットアップ

# 開発環境構築 (フロント・バックエンド共通)
[tasks.setup]
description = "Setup the common development environment"
run = "mise i"

# サーバー開発環境構築
[tasks.setup-server-dev]
description = "Setup the sever development environment"
run = """
pip install poetry=='1.8.2' \
&& poetry install \
&& poetry run pre-commit install \
&& poetry run pre-commit install --hook-type commit-msg
"""

# フロント開発環境構築
[tasks.setup-client-dev]
description = "Setup the client development environment"
run = ""


# フロントエンド用コマンド




# バックエンド用コマンド
# コマンドは、server/ディレクトリで行うこと。

# Poetryからrequirements.txtの生成
[tasks.poetry-req]
description = "Generate requirements.txt from poetry"
run = """
poetry export --without-hashes -o requirements.txt \
&& poetry export --without-hashes --with dev -o requirements-dev.txt
"""

# Ruff/フォーマット
[tasks.ruff-fmt]
description = "Format the Python file for Ruff"
run = "poetry run ruff format --force-exclude --config ruff.toml"

# Ruff/リンター
[tasks.ruff]
description = "Lint the Python file for Ruff"
run = "poetry run ruff check --force-exclude --config ruff.toml"

# Ruff/リンター/修正
[tasks.ruff-fix]
description = "Lint the Python file for Ruff"
run = "poetry run ruff check --fix --force-exclude --config ruff.toml"

# mypy
[tasks.mypy]
description = "Check the Python file for mypy"
run = "poetry run mypy --strict --ignore-missing-imports ."
