FROM ubuntu:22.04

ARG USER_NAME="vscode" \
    USER_UID=2000 \
    USER_GID=2000

# Install dependencies
RUN apt update \
    && apt install -y sudo curl git vim wget locales \
    # # LinuxのNPUドライバをビルドするための依存関係
    # && apt install -y gcc make build-essential git-lfs cmake libudev-dev libboost-all-dev \
    # # Linuxカーネルを
    # && apt install -y build-essential flex bison dwarves libssl-dev libelf-dev \
    && groupadd --gid $USER_GID $USER_NAME \
    && useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USER_NAME \
    && echo $USER_NAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USER_NAME \
    && chmod 0440 /etc/sudoers.d/$USER_NAME \
    && localedef -f UTF-8 -i ja_JP ja_JP.UTF-8 \
    && apt clean

# # コマンドラインでLinuxのNPUをビルド
# RUN cd linux-npu-driver \
#     && git submodule update --init --recursive \
#     && cmake -B build -S . \
#     && cmake --build build --parallel $(nproc) \
#     # set the LD_LIBRARY_PATH to lib to make driver visible for loader
#     && export LD_LIBRARY_PATH=$PWD/build/lib:$LD_LIBRARY_PATH \
#     # or install the driver in the system
#     && cmake --install build


# Set the locale
ENV LANG=ja_JP.UTF-8 \
    LANGUAGE=ja_JP:ja \
    LC_ALL=ja_JP.UTF-8 \
    TZ=JST-9

USER $USER_NAME
# Install mise
RUN curl https://mise.run | sh \
    && echo 'export PATH=~/.local/bin:$PATH' >> ~/.bashrc \
    && echo 'eval "$(~/.local/bin/mise activate bash)"' >> ~/.bashrc \
    # Install Starship
    && curl -sS https://starship.rs/install.sh | sh -s -- -y \
    && echo 'eval "$(starship init bash)"' >> ~/.bashrc \
    # Use No Nerd Font
    && mkdir -p ~/.config && touch ~/.config/starship.toml \
    && starship preset no-nerd-font -o ~/.config/starship.toml \
    # Set the prompt
    && echo "[directory]\ntruncation_length=100" >> ~/.config/starship.toml \
    && echo "[git_branch]\nsymbol = '🌱 '" >> ~/.config/starship.toml

WORKDIR /workspace

# Copy the project files
COPY . .

# Allow /workspace for git
RUN git config --global --add safe.directory /workspace \
    && git config --global fetch.prune true

