name: Analyze Python code with Ruff and mypy

on:
  pull_request:
    branches:
      - main
    paths:
      - "**py"

  # 手動でGitHub Acitionsを起動する用
  # 実験のためにつけているので、実装し終えたら消す
  workflow_dispatch:

jobs:
  Check-Ruff-and-mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r server/requirements.txt
        pip install ruff mypy
    - name: Analyze Python code with Ruff
      run: |
        ruff check --output-format=github --config="server/ruff.toml" $(git ls-files '**.py')
    - name: Type checking Python code with mypy
      run: |
        mypy --strict --ignore-missing-imports $(git ls-files '**.py')


